apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  # StorageBucket names must be globally unique
  name: mad-summit-demo
  annotations:
    # required to configure Config Connector with Google Cloud ProjectID
    # only if we deploy it to different namespaces
    # cnrm.cloud.google.com/project-id: cloud-native-experience-lab
    cnrm.cloud.google.com/force-destroy: "false"
  labels:
    stage: demo
spec:
  lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 7
  versioning:
    enabled: true
  uniformBucketLevelAccess: true
